<a href="https://colab.research.google.com/github/ambilisunil/python_basics/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy for Machine Learning & Data Science
NumPy (Numerical Python) is a core library for numerical computing in Python. It's heavily used in Machine Learning, Data Science, and Deep Learning because it provides fast, efficient operations on large datasets.

In [9]:
import numpy as np

In [15]:

# Creating an array
arr = np.array([1, 2.5, 3, 4, 5])
print(arr)  # Output: [1 2 3 4 5]

# Shape & size
print(arr.shape)   # (5,) → 1D array with 5 elements
print(arr.size)    # 5 → Total elements
print(arr.dtype)   # int64 → Data type
print(type(arr))



[1.  2.5 3.  4.  5. ]
(5,)
5
float64
<class 'numpy.ndarray'>


In [13]:
arr[0]

1

In [14]:
type(arr[0])

numpy.int64

In [16]:
type(arr[1])

numpy.float64

# MULTIPLE *DIMESIONAL*

In [19]:
md=np.array([[1,2],[2,3]])
print(md)

[[1 2]
 [2 3]]


# NONES AND ZEROS


>np.ones((m,n)) m*n matrix filled with 1


> np.zeros((m,n)) m*n matrix filled with 0







In [25]:
nones= np.ones((2,2))
print(nones)

[[1. 1.]
 [1. 1.]]


In [24]:
nones= np.ones((2))
print(nones)

[1. 1.]


In [32]:
zeros= np.zeros((4,4))
print(zeros)
print(zeros.shape)
print(type(zeros))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
(4, 4)
<class 'numpy.ndarray'>


# RANDOM NUMBER NUMPY

In [47]:
np.random.random((2,2))   #print 2*2 shape

array([[0.06594282, 0.05614594],
       [0.04073486, 0.48229081]])

MATH OPERTIONS

In [48]:
a=10
b=20

In [49]:
np.add(a,b)

30

In [53]:
np.subtract(10,20)

-10

In [54]:
np.multiply(a,b)

200

In [55]:
np.divide(b,a)

2.0

# CONCATINATE NUMPY

In [56]:
a1= np.array([1,2,3])
a2= np.array([2,3.4])

In [60]:
np.concatenate((a1,a2))

array([1. , 2. , 3. , 2. , 3.4])

**CONCATINATE MULTIPLE DIMENSIONAL**

In [75]:
n1=np.array([[1,2,3],[4,5,6]])
n2=np.array([[7,8,9],[10,11,12]])
print(n1)
print("")

print(n2)
print("")
print(n1.shape)
print(n2.shape)




[[1 2 3]
 [4 5 6]]

[[ 7  8  9]
 [10 11 12]]

(2, 3)
(2, 3)


Vertical Concatenation **(axis=0)**
**Joins arrays top to bottom (row-wise)**
Works for 2D arrays (matrices)


>Horizontal Concatenation **(axis=1)**
Joins arrays side by side **(column-wise)**
Works for 2D arrays (matrices)





In [81]:
n3= np.concatenate((n1,n2),axis=0)  # vertically conactinate
print(n3)
print("")

print(n3.shape)

print("")

n4= np.concatenate((n1,n2),axis=1)  # horizontal conactinate
print(n4,)
print("")

print(n4.shape)



[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

(4, 3)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]

(2, 6)


**hstack** **vstack**- other way of  vertical and horizonatal concatination

In [82]:
hstack=np.hstack((n1,n2))
print(hstack)
print("")
print(hstack.shape)
print("")

vstack=np.vstack((n1,n2))
print(vstack)
print("")
print(vstack.shape)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]

(2, 6)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

(4, 3)


# RESHAPE ARRAY


>NumPy **reshape**(): Changing the Shape of an Array


> The reshape() function in NumPy changes the shape of an array without changing its data.






In [95]:
rs=np.array(([[1,2,32,77],[2,3,0,7]]))
rs.shape

(2, 4)

In [96]:
print(rs)

[[ 1  2 32 77]
 [ 2  3  0  7]]


In [98]:
rs_c=rs.reshape(8)
print(rs_c)
print(rs_c.shape)

[ 1  2 32 77  2  3  0  7]
(8,)


In [106]:
rs_c=np.reshape(rs,(4,2))
print(rs_c)
print(rs_c.shape)

[[ 1  2]
 [32 77]
 [ 2  3]
 [ 0  7]]
(4, 2)


# **flatten()** and  **ravel()** in NumPy 🚀


> Both flatten() and ravel() convert a multi-dimensional array into a 1D array, but they have key differences in memory behavior.


> flatten(): Returns a Copy
Creates a new copy of the data
Changes to the new array do NOT affect the original array
Always allocates new memory



> A Returns a View (If Possible)
Does NOT create a new copy if possible (returns a view instead)
Changes to the ravel() array MAY affect the original array
More memory-efficient






**bold text**

In [117]:
rs=np.array(([[1,2,32,77],[2,3,0,7]]))

flattern =rs.flatten()
ravel= np.ravel(rs)

print(rs)
print(flattern)

print(ravel)


[[ 1  2 32 77]
 [ 2  3  0  7]]
[ 1  2 32 77  2  3  0  7]
[ 1  2 32 77  2  3  0  7]


In [118]:
print(rs)
print("")
print(np.ravel(rs,order="F")) #colum major
print(np.ravel(rs,order="C")) #raw major

[[ 1  2 32 77]
 [ 2  3  0  7]]

[ 1  2  2  3 32  0 77  7]
[ 1  2 32 77  2  3  0  7]


# **EXPAND**

In [120]:
a=np.array([100,200,300])
print(a)
print(a.shape)

[100 200 300]
(3,)


In [121]:
a1=np.expand_dims(a,axis=0)
print(a1)
print(a1.shape)

[[100 200 300]]
(1, 3)


In [122]:
a2=np.expand_dims(a,axis=1)
print(a2)
print(a2.shape)


[[100]
 [200]
 [300]]
(3, 1)


# TRANSPONSE:


> NumPy transpose() and** .**T: Swapping Axes of an Array 🚀
transpose() is used to swap the dimensions (axes) of a NumPy array, often for matrix operations, deep learning, and broadcasting.


> raws are colums and columns arev raws





In [126]:

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

transposed = np.transpose(arr) #mthd   1



print(transposed)
print("  ")
print(arr.T)  #mthd 2


[[1 4]
 [2 5]
 [3 6]]
  
[[1 4]
 [2 5]
 [3 6]]


# UNIQUE

**NumPy unique()**: Finding Unique Elements in an Array

np.unique() is used to find unique elements in a NumPy array.

It can also return additional information, like counts and indices.



In [127]:
arr = np.array([1, 2, 2, 3, 4, 4, 4, 5])
unique_values = np.unique(arr)

print(unique_values)

[1 2 3 4 5]


return_counts: Count of Each Unique Element


In [128]:
unique_values, counts = np.unique(arr, return_counts=True)
print(unique_values)  # [1 2 3 4 5]
print(counts)         # [1 2 1 3 1]

[1 2 3 4 5]
[1 2 1 3 1]
